version: '3.8'

services:
  app:
    image: node:16.20.1-alpine
    container_name: proofr
    working_dir: /app
    command: node server.js
    environment:
      FRONTEND_PORT: ${FRONTEND_PORT}
      BACKEND_PORT: ${BACKEND_PORT}
      ENV: ${ENV}
    volumes:
      - .:/app
    networks:
      - internal

networks:
  internal:
    external: true